name: Check links

on:
  workflow_dispatch:
  schedule:
    # Every Monday
    - cron: "0 7 7 * *"

permissions:
  contents: read

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Check links
        uses: ./.github/actions/check-links
